// <auto-generated />
using System;
using CoachTwinsApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoachTwinsApi.Db.Migrations
{
    [DbContext(typeof(CoachTwinsDbContext))]
    [Migration("20211013090610_CriteriaSystem")]
    partial class CriteriaSystem
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Appointment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Criteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Category", "Value");

                    b.ToTable("Criteria");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FirstAppointmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("MatchedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("CoachId");

                    b.HasIndex("FirstAppointmentId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.MatchingCriteria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CriteriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("Prefer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("UserId");

                    b.ToTable("MatchingCriteria");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SendAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("SourceId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingYear")
                        .HasColumnType("int");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Coach", b =>
                {
                    b.HasBaseType("CoachTwinsApi.Db.Entities.User");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Student", b =>
                {
                    b.HasBaseType("CoachTwinsApi.Db.Entities.User");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasFilter("[MatchId] IS NOT NULL");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Match", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.Chat", "Chat")
                        .WithMany()
                        .HasForeignKey("ChatId");

                    b.HasOne("CoachTwinsApi.Db.Entities.Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("CoachId");

                    b.HasOne("CoachTwinsApi.Db.Entities.Appointment", "FirstAppointment")
                        .WithMany()
                        .HasForeignKey("FirstAppointmentId");

                    b.Navigation("Chat");

                    b.Navigation("Coach");

                    b.Navigation("FirstAppointment");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.MatchingCriteria", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.Criteria", "Criteria")
                        .WithMany()
                        .HasForeignKey("CriteriaId");

                    b.HasOne("CoachTwinsApi.Db.Entities.User", "User")
                        .WithMany("MatchingCriteria")
                        .HasForeignKey("UserId");

                    b.Navigation("Criteria");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Message", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.Chat", null)
                        .WithMany("Messages")
                        .HasForeignKey("ChatId");

                    b.HasOne("CoachTwinsApi.Db.Entities.User", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Coach", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("CoachTwinsApi.Db.Entities.Coach", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Student", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("CoachTwinsApi.Db.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("CoachTwinsApi.Db.Entities.Match", "Match")
                        .WithOne("Student")
                        .HasForeignKey("CoachTwinsApi.Db.Entities.Student", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Match", b =>
                {
                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.User", b =>
                {
                    b.Navigation("MatchingCriteria");
                });
#pragma warning restore 612, 618
        }
    }
}
