// <auto-generated />
using System;
using CoachTwinsApi.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoachTwinsApi.Db.Migrations
{
    [DbContext(typeof(CoachTwinsDbContext))]
    [Migration("20211001084236_seperate_inheritance_into_tables")]
    partial class seperate_inheritance_into_tables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Interest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Interests");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingYear")
                        .HasColumnType("int");

                    b.Property<string>("StudentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityProgram")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Coach", b =>
                {
                    b.HasBaseType("CoachTwinsApi.Db.Entities.User");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Student", b =>
                {
                    b.HasBaseType("CoachTwinsApi.Db.Entities.User");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Interest", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.User", null)
                        .WithMany("Interests")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Coach", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("CoachTwinsApi.Db.Entities.Coach", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.Student", b =>
                {
                    b.HasOne("CoachTwinsApi.Db.Entities.User", null)
                        .WithOne()
                        .HasForeignKey("CoachTwinsApi.Db.Entities.Student", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CoachTwinsApi.Db.Entities.User", b =>
                {
                    b.Navigation("Interests");
                });
#pragma warning restore 612, 618
        }
    }
}
